inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.3

  Exclude:
     - 'db/migrate/*'
     - 'vebdor/**/*'
     - 'node_modules/**/*'
     - 'test/**/*'
     - 'db/**/*'
     - 'spec/**/*'
     - 'bin/**'
     - 'config/**/*'

Layout/LineLength:
   Max: 90

AsciiComments:
   Enabled: false
