inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.4

  Exclude:
     - 'db/migrate/*'
     - 'vebdor/**/*'
     - 'node_modules/**/*'
     - 'test/**/*'
     - 'db/**/*'

Layout/LineLength:
    Max: 90
