inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**"
    - "db/migrate/*"
    - "db/schema.rb"
    - "config/puma.rb"
    - "lib/**"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "shared/**/*"
    - "lib/tasks/auto_annotate_models.rake"
  TargetRubyVersion: 2.6.4

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 155

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/SwapValues:
  Enabled: true

Style/GlobalStdStream:
  Exclude:
    - "config/environments/production.rb"

Security/Open:
  Exclude:
    - "db/seeds.rb"

Style/IdenticalConditionalBranches:
  Exclude:
    - "app/controllers/users_controller.rb"

Rails/InverseOf:
  Enabled: false

Rails/FilePath:
  Enabled: false

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

# Lint/EmptyBlock:
#   Enabled: true
#   Exclude:
#     - "config/deploy.rb"

Lint/ToEnumArguments:
  Enabled: true

Lint/UselessAssignment:
  Enabled: false

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 200

Metrics/MethodLength:
  Max: 11
