inherit_from: .rubocop_todo.yml

require:
   - rubocop-rails

AllCops:
   TargetRubyVersion: 2.6

   Exclude:
      - 'db/migrate/*'
      - 'vebdor/**/*'
      - 'node_modules/**/*'
      - 'test/**/*'
      - 'db/**/*'
      - 'spec/**/*'
      - 'bin/**'
      - 'config/**/*'

# Style/Documentation:
#    Enabled: false

Style/ClassAndModuleChildren:
   Enabled: false

Layout/LineLength:
   Max: 120

Style/FrozenStringLiteralComment:
   Enabled: false

Style/AsciiComments:
   Enabled: false
