version: "3"
services:
  db:
    image: mysql:8.0.19
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      RAILS_ENV: development
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/Contrail
      - sockets:/Contrail/tmp/sockets
      - log_data:/Contrail/log
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - public-data:/Contrail/public
      - tmp-data:/Contrail/tmp
      - sockets:/Contrail/tmp/sockets
    ports:
      - 80:80
    depends_on:
      - web
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - "./app/redis:/data"

volumes:
  mysql_data:
  log_data:
  public-data:
  tmp-data:
  sockets:
