version: '3'
services:
  db:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  web:
    build: .
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Contrail
    ports:
      - 3000:3000
    depends_on:
      - db
  #nginx:
  #  build:
  #    context: .
  #    dockerfile: ./nginx/Dockerfile
  #  volumes:
  #    - public-data:/Contrail/public
  #    - tmp-data:/Contrail/tmp
  #    - sockets:/Contrail/tmp/sockets 
  #  ports: 
  #    - 80:80
  #  depends_on:
  #    - web
#volumes:
#  public-data:
#  tmp-data:
#  sockets:
