default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket:   /tmp/mysql.sock
  username: root
  host: db
  password: <%= ENV['ROOT_PASS'] %>



development:
  <<: *default
  database: <%= ENV['DB_NAME_DEV'] %>
  username: root
  password: <%= ENV['DB_DEV_PASSWORD'] %>
  host:     db

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] %>
  host:     localhost

production:
  <<: *default
  database: sample
  username: sample
  password: <%= ENV['DB_SAMPLE_PASSWORD']
  host:     sample
