default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock
  username: root
  host: localhost
  password: <%= ENV['RDS_DEV_PASS'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME_DEV'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] %>

production:
  <<: *default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: <%= Rails.application.credentials.production[:rds_database] %>
  host:     <%= Rails.application.credentials.production[:rds_endpoint] %>
  username: <%= Rails.application.credentials.production[:rds_username] %>
  password: <%= Rails.application.credentials.production[:rds_passwd] %>
  socket: /var/lib/mysql/mysql.sock
