default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock
  username: root
  host: localhost
  password: <%= ENV['ROOT_PASS'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME_DEV'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] %>

production:
  <<: *default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: sample
  username: root
  password: <%= Rails.application.credentials.production[:db_passwd] %>
  socket: /var/lib/mysql/mysql.sock
