default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock
  username: root
  host: db
  password:

development:
  <<: *default
  database: contrail_development

test:
  <<: *default
  database: contrail_test

production:
  <<: *default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: <%= Rails.application.credentials.production[:rds_database] %>
  host:     <%= Rails.application.credentials.production[:rds_endpoint] %>
  username: <%= Rails.application.credentials.production[:rds_username] %>
  password: <%= Rails.application.credentials.production[:rds_passwd] %>
  socket: /var/lib/mysql/mysql.sock
