default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock
  username: root
  host: localhost
  password: <%= ENV['ROOT_PASS'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME_DEV'] %>
  username: root
  password: <%= ENV['ROOT_PASS'] %>
  host: localhost

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] %>
  host: localhost

production:
  <<: *default
  database: sample
  username: root
  password:
<<<<<<< HEAD
=======
  host:     sample
>>>>>>> 78374cae0e751cea069a771d926cab76a8438f73
